import { useEffect, useState, type ReactNode } from 'react'
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import {
  Bell, Bookmark, CalendarDays, Check, ChevronRight, CircleDot, Compass, Heart, Home,
  ImagePlus, Menu, MessageCircle, MoreHorizontal, PenLine, Plus, Search, Send, Settings,
  Share2, Sparkles, Users, X, Zap,
} from 'lucide-react'
import { activities, circles, currentUser, intentColor, intents, posts, users } from './data'
import type { Activity, Circle, Intent, Post, User } from './types'

const navItems = [
  { to: '/', label: 'Home', icon: Home }, { to: '/discover', label: 'Discover', icon: Compass },
  { to: '/create', label: 'Create', icon: PenLine }, { to: '/matches', label: 'Matches', icon: Heart },
  { to: '/circles', label: 'Circles', icon: Users }, { to: '/activities', label: 'Activities', icon: CalendarDays },
  { to: '/messages', label: 'Messages', icon: MessageCircle },
]

function useStoredState<T>(key: string, initial: T) {
  const [value, setValue] = useState<T>(() => {
    try { return JSON.parse(localStorage.getItem(key) ?? '') as T } catch { return initial }
  })
  useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value])
  return [value, setValue] as const
}

function App() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [activeIntent, setActiveIntent] = useStoredState<Intent>('circle-intent', 'Build')
  const [feedPosts, setFeedPosts] = useStoredState<Post[]>('circle-posts', posts)
  const [liked, setLiked] = useStoredState<number[]>('circle-liked', [])
  const [joinedActivities, setJoinedActivities] = useStoredState<number[]>('circle-activities', [2])
  const [joinedCircles, setJoinedCircles] = useStoredState<number[]>('circle-circles', [1, 4])
  const [toast, setToast] = useState('')
  const location = useLocation()
  const showToast = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  useEffect(() => setMobileOpen(false), [location.pathname])
  return <div className="app-shell">
    <Sidebar activeIntent={activeIntent} onIntent={setActiveIntent} mobileOpen={mobileOpen} onClose={() => setMobileOpen(false)} />
    <div className="mobile-header"><button className="icon-btn" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={21} /></button><Logo /><Link to="/profile" className="avatar-link"><img src={currentUser.avatar} alt="Open your profile" /></Link></div>
    <main className="main-area">
      <Routes>
        <Route path="/" element={<HomePage activeIntent={activeIntent} setIntent={setActiveIntent} feedPosts={feedPosts} liked={liked} setLiked={setLiked} showToast={showToast} />} />
        <Route path="/discover" element={<DiscoverPage />} />
        <Route path="/create" element={<CreatePage showToast={showToast} onPublished={(data) => setFeedPosts([{ id: Date.now(), author: currentUser, body: data.body, intent: data.intent, topic: data.topic, time: 'now', likes: 0, comments: 0, saves: 0 }, ...feedPosts])} />} />
        <Route path="/matches" element={<MatchesPage showToast={showToast} />} />
        <Route path="/circles" element={<CirclesPage joined={joinedCircles} setJoined={setJoinedCircles} showToast={showToast} />} />
        <Route path="/activities" element={<ActivitiesPage joined={joinedActivities} setJoined={setJoinedActivities} showToast={showToast} />} />
        <Route path="/messages" element={<MessagesPage />} />
        <Route path="/profile" element={<ProfilePage />} />
      </Routes>
    </main>
    <MobileNav />
    {toast && <div className="toast" role="status"><Check size={16} />{toast}</div>}
  </div>
}

function Logo() { return <Link to="/" className="logo"><span className="logo-mark"><CircleDot size={20} /></span><span>CIRCLE</span></Link> }

function Sidebar({ activeIntent, onIntent, mobileOpen, onClose }: { activeIntent: Intent; onIntent: (intent: Intent) => void; mobileOpen: boolean; onClose: () => void }) {
  return <><aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}><div className="sidebar-top"><Logo /><button className="icon-btn close-mobile" onClick={onClose} aria-label="Close navigation"><X size={20} /></button></div><div className="intent-switcher"><span className="eyebrow">Your current intent</span><button className="intent-current" style={{ '--intent': intentColor(activeIntent) } as React.CSSProperties} onClick={() => onIntent(activeIntent === 'Build' ? 'Explore' : 'Build')}><span className="intent-spark">{intents.find((intent) => intent.name === activeIntent)?.icon}</span><span>{activeIntent}</span><ChevronRight size={15} /></button><p>Tap to switch your signal</p></div><nav className="nav-list" aria-label="Primary navigation">{navItems.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><Icon size={18} strokeWidth={1.8} /><span>{label}</span>{label === 'Messages' && <b className="nav-count">3</b>}</NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/profile" className="profile-mini"><img src={currentUser.avatar} alt="" /><span><strong>{currentUser.name}</strong><small>{currentUser.handle}</small></span><MoreHorizontal size={17} /></NavLink><button className="nav-item settings"><Settings size={18} /><span>Settings</span></button></div></aside>{mobileOpen && <button className="sidebar-scrim" onClick={onClose} aria-label="Close menu" />}</>
}

function MobileNav() { return <nav className="mobile-nav" aria-label="Mobile navigation">{navItems.slice(0, 5).map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} className={({ isActive }) => isActive ? 'active' : ''}><Icon size={19} /><span>{label}</span></NavLink>)}</nav> }

function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: ReactNode; description?: string; action?: ReactNode }) { return <header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</header> }
function IntentPill({ intent }: { intent: Intent }) { return <span className="intent-pill" style={{ '--intent': intentColor(intent) } as React.CSSProperties}><i />{intent}</span> }
function Avatar({ user, size = 'md' }: { user: User; size?: 'sm' | 'md' | 'lg' }) { return <span className={`avatar ${size}`}><img src={user.avatar} alt={`${user.name}'s avatar`} />{user.online && <i className="online-dot" />}</span> }
function SectionTitle({ title, action }: { title: string; action?: string }) { return <div className="section-title"><h2>{title}</h2>{action && <button className="text-btn">{action}<ChevronRight size={15} /></button>}</div> }

function HomePage({ activeIntent, setIntent, feedPosts, liked, setLiked, showToast }: { activeIntent: Intent; setIntent: (value: Intent) => void; feedPosts: Post[]; liked: number[]; setLiked: (value: number[]) => void; showToast: (message: string) => void }) {
  return <div className="page"><div className="topbar"><div className="search-box"><Search size={17} /><input placeholder="Search your circles..." aria-label="Search your circles" /></div><div className="top-actions"><button className="icon-btn notification-btn" aria-label="Notifications"><Bell size={19} /><i /></button><button className="avatar-button" aria-label="Open your profile"><Avatar user={currentUser} size="sm" /></button></div></div><PageHeader eyebrow="Wednesday, September 9" title={<>Make something <span className="gradient-text">meaningful.</span></>} description="A little momentum from people moving in your direction." action={<Link to="/create" className="primary-btn"><Plus size={17} />Share an idea</Link>} /><section className="intent-hero"><div><span className="eyebrow">The signal you are sending</span><h2>I want to <strong>{activeIntent.toLowerCase()}</strong> with people who care.</h2><p>Change your intent whenever your curiosity changes. Your feed follows.</p></div><div className="intent-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-core" style={{ '--intent': intentColor(activeIntent) } as React.CSSProperties}>{intents.find((intent) => intent.name === activeIntent)?.icon}</div><div className="orbit-label">{activeIntent}</div></div></section><div className="intent-tabs" role="tablist" aria-label="Choose your intent">{intents.map((intent) => <button key={intent.name} role="tab" aria-selected={activeIntent === intent.name} className={activeIntent === intent.name ? 'selected' : ''} style={{ '--intent': intent.color } as React.CSSProperties} onClick={() => setIntent(intent.name)}>{intent.icon} <span>{intent.name}</span></button>)}</div><div className="content-grid"><section><SectionTitle title="For you" action="Tune feed" />{feedPosts.map((post) => <PostCard key={post.id} post={post} liked={liked.includes(post.id)} onLike={() => setLiked(liked.includes(post.id) ? liked.filter((id) => id !== post.id) : [...liked, post.id])} onAction={showToast} />)}</section><aside className="right-column"><SectionTitle title="People in your orbit" action="See all" />{users.slice(0, 3).map((user) => <PersonRow key={user.id} user={user} onAction={showToast} />)}<div className="mini-invite"><Sparkles size={19} /><div><strong>Your signal is clear.</strong><p>8 new people are looking to {activeIntent.toLowerCase()}.</p></div><ChevronRight size={17} /></div><SectionTitle title="Active circles" action="Explore" />{circles.slice(0, 2).map((circle) => <CircleRow key={circle.id} circle={circle} />)}</aside></div></div>
}

function PostCard({ post, liked, onLike, onAction }: { post: Post; liked: boolean; onLike: () => void; onAction: (message: string) => void }) { return <article className="post-card"><div className="post-head"><Avatar user={post.author} /><div className="author-meta"><strong>{post.author.name}<span className="verified">✓</span></strong><small>{post.author.handle} · {post.time}</small></div><button className="icon-btn subtle" aria-label="More post actions"><MoreHorizontal size={18} /></button></div><div className="post-body"><div className="post-topic"><IntentPill intent={post.intent} /><span>{post.topic}</span></div><p>{post.body}</p></div><div className="post-actions"><button className={liked ? 'action active' : 'action'} onClick={onLike}><Heart size={17} fill={liked ? 'currentColor' : 'none'} />{post.likes + (liked ? 1 : 0)}</button><button className="action" onClick={() => onAction('Reply composer opened')}><MessageCircle size={17} />{post.comments}</button><button className="action" onClick={() => onAction('Post saved to your orbit')}><Bookmark size={17} />{post.saves}</button><button className="action action-share" onClick={() => onAction('Share link copied')}><Share2 size={17} /></button></div></article> }
function PersonRow({ user, onAction }: { user: User; onAction: (message: string) => void }) { return <div className="person-row"><Avatar user={user} size="sm" /><div><strong>{user.name}<span className="verified">✓</span></strong><small>{user.intents.join(' · ')} · {user.location}</small></div><button className="outline-btn small" onClick={() => onAction(`Connected with ${user.name}`)}>Connect</button></div> }
function CircleRow({ circle }: { circle: Circle }) { return <Link to="/circles" className="circle-row"><span className="circle-icon" style={{ '--intent': circle.accent } as React.CSSProperties}><Users size={18} /></span><span><strong>{circle.name}</strong><small>{circle.members} members · {circle.online} online</small></span><ChevronRight size={16} /></Link> }

function DiscoverPage() { const [query, setQuery] = useState(''); const [selectedIntent, setSelectedIntent] = useState<Intent | null>(null); const [connected, setConnected] = useState<number[]>([]); const filtered = users.filter((user) => `${user.name} ${user.bio} ${user.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (!selectedIntent || user.intents.includes(selectedIntent))); return <div className="page"><PageHeader eyebrow="Find your people" title="Discover with intention." description="Search by what you want to do, not who you already know." /><div className="discover-search"><Search size={19} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try “creative coding” or “people building in public”" /></div><div className="filter-row" role="group" aria-label="Filter people by intent">{intents.map((intent) => <button key={intent.name} aria-pressed={selectedIntent === intent.name} className={`filter-chip ${selectedIntent === intent.name ? 'selected' : ''}`} onClick={() => setSelectedIntent(selectedIntent === intent.name ? null : intent.name)}><span style={{ color: intent.color }}>{intent.icon}</span>{intent.name}</button>)}</div><div className="discover-layout"><section><SectionTitle title="People to meet" action={`${filtered.length} nearby`} />{filtered.length ? filtered.map((user) => <div className="discover-person" key={user.id}><Avatar user={user} size="lg" /><div className="discover-person-copy"><div className="row-between"><div><h3>{user.name} <span className="verified">✓</span></h3><small>{user.handle} · {user.location}</small></div><strong className="match-score">{90 - user.id * 3}% <small>match</small></strong></div><p>{user.bio}</p><div className="tag-row">{user.intents.map((intent) => <IntentPill key={intent} intent={intent} />)}{user.skills.map((skill) => <span className="soft-tag" key={skill}>{skill}</span>)}</div></div><button className={connected.includes(user.id) ? 'joined-btn' : 'outline-btn'} onClick={() => setConnected(connected.includes(user.id) ? connected.filter((id) => id !== user.id) : [...connected, user.id])}>{connected.includes(user.id) && <Check size={15} />}{connected.includes(user.id) ? 'Connected' : 'Connect'}</button></div>) : <div className="empty-state"><Search size={22} /><strong>No people match that signal yet.</strong><p>Try another intent or clear your search.</p></div>}</section><aside className="trend-panel"><SectionTitle title="Trending now" /><div className="trend-item"><span>01</span><div><strong>#buildinpublic</strong><small>1.8k people exploring</small></div><ChevronRight size={15} /></div><div className="trend-item"><span>02</span><div><strong>Creative constraints</strong><small>642 conversations</small></div><ChevronRight size={15} /></div><div className="trend-item"><span>03</span><div><strong>Slow tech</strong><small>214 new signals</small></div><ChevronRight size={15} /></div></aside></div></div> }

const postSchema = z.object({ body: z.string().min(12, 'Share a little more so people can find the thread.').max(500, 'Keep it under 500 characters.'), intent: z.enum(['Build', 'Learn', 'Create', 'Explore', 'Play', 'Discuss']), topic: z.string().min(2, 'Add a topic.') })
type PostForm = z.infer<typeof postSchema>
function CreatePage({ showToast, onPublished }: { showToast: (message: string) => void; onPublished: (data: PostForm) => void }) { const { register, handleSubmit, watch, formState: { errors } } = useForm<PostForm>({ resolver: zodResolver(postSchema), defaultValues: { intent: 'Build', topic: '' } }); const body = watch('body') ?? ''; const onSubmit = (data: PostForm) => { onPublished(data); localStorage.setItem('circle-last-post', JSON.stringify(data)); showToast('Your idea is now in the orbit') }; return <div className="page narrow-page"><PageHeader eyebrow="Put something into the world" title="Start a thread." description="The best posts begin with a real intention, a useful question, or a spark worth sharing." /><form className="create-card" onSubmit={handleSubmit(onSubmit)}><div className="create-author"><Avatar user={currentUser} /><div><strong>{currentUser.name}</strong><small>Posting to For you</small></div><span className="draft-status">Draft saved</span></div><label className="field-label" htmlFor="post-body">What are you moving toward?</label><textarea id="post-body" {...register('body')} placeholder="Share a progress note, a question, or an idea..." /><div className="field-footer"><span className={body.length > 450 ? 'danger-text' : ''}>{body.length}/500</span><button type="button" className="icon-btn" aria-label="Add image"><ImagePlus size={19} /></button></div>{errors.body && <span className="error-text">{errors.body.message}</span>}<div className="form-grid"><label className="field-label">Intent<select {...register('intent')}>{intents.map((intent) => <option key={intent.name}>{intent.name}</option>)}</select></label><label className="field-label">Topic<input {...register('topic')} placeholder="e.g. Product thinking" />{errors.topic && <span className="error-text">{errors.topic.message}</span>}</label></div><div className="create-actions"><button type="button" className="outline-btn" onClick={() => showToast('Draft saved locally')}>Save draft</button><button className="primary-btn" type="submit"><Zap size={16} />Publish thread</button></div></form><div className="prompt-strip"><Sparkles size={18} /><p><strong>A good prompt to start:</strong> “What is something you are learning right now that you wish more people were talking about?”</p></div></div> }

function MatchesPage({ showToast }: { showToast: (message: string) => void }) { return <div className="page"><PageHeader eyebrow="Your strongest overlaps" title="Matches with momentum." description="Compatibility here is about direction, not popularity." /><div className="match-hero"><div><span className="eyebrow">Your signal strength</span><strong>84%</strong><p>People who want to build and explore alongside you.</p></div><div className="match-bars"><span style={{ width: '84%' }} /><span style={{ width: '68%' }} /><span style={{ width: '52%' }} /></div></div><div className="match-grid">{users.map((user) => <article className="match-card" key={user.id}><div className="match-card-top"><Avatar user={user} size="lg" /><div><strong>{user.name}<span className="verified">✓</span></strong><small>{user.location}</small></div><span className="score-ring">{97 - user.id * 4}%</span></div><p>{user.bio}</p><div className="shared-line"><Sparkles size={14} />{user.intents[0]} overlaps with your signal</div><div className="tag-row">{user.skills.slice(0, 3).map((skill) => <span className="soft-tag" key={skill}>{skill}</span>)}</div><div className="match-actions"><button className="outline-btn" onClick={() => showToast(`Connected with ${user.name}`)}>Connect</button><Link to="/messages" className="primary-btn"><MessageCircle size={15} />Message</Link></div></article>)}</div></div> }

function CirclesPage({ joined, setJoined, showToast }: { joined: number[]; setJoined: (value: number[]) => void; showToast: (message: string) => void }) { const toggle = (id: number, name: string) => { const next = joined.includes(id) ? joined.filter((item) => item !== id) : [...joined, id]; setJoined(next); showToast(`${joined.includes(id) ? 'Left' : 'Joined'} ${name}`) }; return <div className="page"><PageHeader eyebrow="Shared momentum" title="Find your circle." description="Small groups built around a thing people are actively trying to do." action={<button className="primary-btn"><Plus size={17} />Create a circle</button>} /><div className="circle-feature"><div><span className="eyebrow">Circle of the week</span><h2>AI Builders Lab</h2><p>Ship small, learn loudly, and keep each other moving. The place for your next brave first version.</p><div className="avatar-stack">{users.slice(0, 4).map((user) => <Avatar key={user.id} user={user} size="sm" />)}<span>+243</span></div></div><div className="feature-glyph"><Sparkles size={34} /></div></div><div className="card-grid">{circles.map((circle) => <article className="circle-card" key={circle.id}><div className="circle-card-icon" style={{ '--intent': circle.accent } as React.CSSProperties}><Users size={22} /></div><div className="row-between"><IntentPill intent={circle.intent} /><span className="online-copy">● {circle.online} online</span></div><h3>{circle.name}</h3><p>{circle.description}</p><div className="card-meta"><span>{circle.members} members</span><button className={joined.includes(circle.id) ? 'joined-btn' : 'outline-btn'} onClick={() => toggle(circle.id, circle.name)}>{joined.includes(circle.id) && <Check size={15} />}{joined.includes(circle.id) ? 'Joined' : 'Join circle'}</button></div></article>)}</div></div> }

function ActivitiesPage({ joined, setJoined, showToast }: { joined: number[]; setJoined: (value: number[]) => void; showToast: (message: string) => void }) { const toggle = (activity: Activity) => { setJoined(joined.includes(activity.id) ? joined.filter((id) => id !== activity.id) : [...joined, activity.id]); showToast(`${joined.includes(activity.id) ? 'Removed from' : 'Added to'} ${activity.title}`) }; return <div className="page"><PageHeader eyebrow="Make time for it" title="Activities with a pulse." description="A calendar of things worth showing up for." action={<button className="outline-btn"><CalendarDays size={16} />My calendar</button>} /><div className="activity-list">{activities.map((activity) => <article className="activity-card" key={activity.id}><div className="date-block"><span>{activity.date.split(' ')[0]}</span><strong>{activity.date.split(' ')[1]?.replace(',', '') ?? 'SEP'}</strong></div><div className="activity-copy"><div className="row-between"><IntentPill intent={activity.intent} /><span className="participant-count"><Users size={14} />{activity.participants}/{activity.capacity}</span></div><h2>{activity.title}</h2><p>{activity.description}</p><div className="activity-details"><span><CalendarDays size={15} />{activity.date}</span><span><Compass size={15} />{activity.location}</span></div></div><button className={joined.includes(activity.id) ? 'joined-btn' : 'primary-btn'} onClick={() => toggle(activity)}>{joined.includes(activity.id) ? <><Check size={15} />Going</> : 'Join activity'}</button></article>)}</div></div> }

function MessagesPage() { const [draft, setDraft] = useState(''); const [sent, setSent] = useState<string[]>([]); const sendMessage = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const message = draft.trim(); if (!message) return; setSent((current) => [...current, message]); setDraft(''); }; return <div className="page"><PageHeader eyebrow="Your conversations" title="Keep the thread going." description="Messages that began with a shared direction." /><div className="messages-layout"><aside className="conversation-list"><div className="conversation-search"><Search size={16} /><input placeholder="Search messages" aria-label="Search messages" /></div>{users.slice(0, 4).map((user, index) => <Link to="/messages" className={`conversation ${index === 0 ? 'selected' : ''}`} key={user.id}><Avatar user={user} size="sm" /><span><strong>{user.name}</strong><small>{index === 0 ? 'The RAG prototype is looking good...' : 'Let’s make something together.'}</small></span><time>{index + 1}h</time></Link>)}</aside><section className="chat-panel"><div className="chat-head"><Avatar user={users[0]} /><div><strong>{users[0].name}</strong><small><i className="online-dot" /> Active now</small></div><button type="button" className="icon-btn" aria-label="More conversation actions"><MoreHorizontal size={19} /></button></div><div className="chat-messages"><div className="message received">Hey Alex, your post about intentional interfaces really stuck with me.<small>10:42 AM</small></div><div className="message sent">That means a lot. I’m trying to make the product feel like an invitation, not another feed.</div><div className="message received">Exactly. Want to swap notes over a quick build session this week?<small>10:45 AM</small></div>{sent.map((message, index) => <div className="message sent" key={`${message}-${index}`}>{message}<small>now</small></div>)}</div><form className="message-form" onSubmit={sendMessage}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write a message..." aria-label="Write a message" /><button className="primary-btn" type="submit" aria-label="Send message"><Send size={16} /></button></form></section></div></div> }

function ProfilePage() { const [editing, setEditing] = useState(false); const [name, setName] = useStoredState('circle-profile-name', currentUser.name); const [bio, setBio] = useStoredState('circle-profile-bio', currentUser.bio); return <div className="page profile-page"><div className="profile-cover" /><div className="profile-header"><Avatar user={currentUser} size="lg" /><div>{editing ? <input className="profile-edit-input" value={name} onChange={(event) => setName(event.target.value)} aria-label="Profile name" /> : <h1>{name}</h1>}<p>{currentUser.handle} · {currentUser.location}</p></div><button className="outline-btn" onClick={() => setEditing(!editing)}>{editing ? <><Check size={16} />Done</> : <><Settings size={16} />Edit profile</>}</button></div>{editing ? <textarea className="profile-edit-bio" value={bio} onChange={(event) => setBio(event.target.value)} aria-label="Profile bio" /> : <p className="profile-bio">{bio}</p>}<div className="profile-stats"><span><strong>128</strong> connections</span><span><strong>6</strong> circles</span><span><strong>24</strong> threads</span></div><div className="profile-intents"><SectionTitle title="My active intents" /><div className="intent-tabs">{currentUser.intents.map((intent) => <div key={intent} className="profile-intent"><span style={{ color: intentColor(intent) }}>{intents.find((item) => item.name === intent)?.icon}</span><strong>{intent}</strong><small>{intents.find((item) => item.name === intent)?.prompt}</small></div>)}</div></div><SectionTitle title="Recent threads" action="View all" />{posts.slice(0, 2).map((post) => <PostCard key={post.id} post={post} liked={false} onLike={() => undefined} onAction={() => undefined} />)}</div> }

export default App
